# Generated by Django 5.2.8 on 2026-05-06 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(help_text='Short tagline shown on the home card (1-2 sentences).', max_length=300)),
                ('tech', models.CharField(blank=True, help_text='Stack list, e.g. "Python · Django · AWS Lambda".', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Full description (Markdown). Shown on the project detail page.')),
                ('cover_image', models.ImageField(help_text='Image shown on the home page card.', upload_to='projects/cover/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True, help_text='Optional live-demo link.')),
                ('youtube_url', models.URLField(blank=True, help_text='Optional YouTube demo video URL — embedded on the detail page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page featured grid.')),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.project')),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
    ]
